name: Release debug apk

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup-java:
    name: Setup Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

  build-debug-apk:
    name: Build debug apk
    needs: [ setup-java ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Debug APK
        run: ./gradlew assembleDebug

  upload-debug-apk:
    name: Upload debug apk
    needs: [ build-debug-apk ]
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifact
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: New-build
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
